spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://localhost:5432/todayit?currentSchema=todayit
    username: todayit_user
    password: todayit1234

todayit:
  security:
    jwt:
      secret: ${JWT_SECRET:01234567890123456789012345678901}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30m}

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
scalar:
  enabled: ${OPENAPI_ENABLED:false}
