CREATE TABLE course (
    course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    title VARCHAR(100) NOT NULL,
    course_summary VARCHAR(500),
    transport VARCHAR(30) NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    visibility VARCHAR(20) NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_course_member
        FOREIGN KEY (member_id) REFERENCES member (member_id),
    CONSTRAINT ck_course_transport
        CHECK (transport IN ('CAR', 'WALKING', 'PUBLIC_TRANSPORT')),
    CONSTRAINT ck_course_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'DELETED')),
    CONSTRAINT ck_course_visibility
        CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

CREATE TABLE course_place (
    course_place_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL,
    place_id INTEGER NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    stay_minute INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_course_place_course
        FOREIGN KEY (course_id) REFERENCES course (course_id),
    CONSTRAINT fk_course_place_place
        FOREIGN KEY (place_id) REFERENCES place (place_id),
    CONSTRAINT uk_course_place_course_order UNIQUE (course_id, "order")
);
