CREATE TABLE region_place (
    region_place_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id INTEGER NOT NULL,
    place_id INTEGER NOT NULL,
    CONSTRAINT fk_region_place_region
        FOREIGN KEY (region_id) REFERENCES region (region_id),
    CONSTRAINT fk_region_place_place
        FOREIGN KEY (place_id) REFERENCES place (place_id)
);
