CREATE TABLE region (
    region_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    si VARCHAR(20) NOT NULL,
    gun VARCHAR(20) NOT NULL,
    gu VARCHAR(30) NOT NULL
);

CREATE TABLE region_place (
    region_place_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id INTEGER NOT NULL,
    place_id INTEGER NOT NULL,
    CONSTRAINT fk_region_place_region
        FOREIGN KEY (region_id) REFERENCES region (region_id),
    CONSTRAINT fk_region_place_place
        FOREIGN KEY (place_id) REFERENCES place (place_id)
);
